--
-- PostgreSQL database dump
--

-- Dumped from database version 14.3
-- Dumped by pg_dump version 14.3

-- Started on 2024-01-17 21:52:43

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 210 (class 1259 OID 32848)
-- Name: categoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categoria (
    "idCategoria" integer NOT NULL,
    "catNombre" text NOT NULL
);


ALTER TABLE public.categoria OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 32847)
-- Name: categoria_idCategoria_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."categoria_idCategoria_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."categoria_idCategoria_seq" OWNER TO postgres;

--
-- TOC entry 3345 (class 0 OID 0)
-- Dependencies: 209
-- Name: categoria_idCategoria_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."categoria_idCategoria_seq" OWNED BY public.categoria."idCategoria";


--
-- TOC entry 217 (class 1259 OID 32906)
-- Name: categoria_idCategoria_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categoria ALTER COLUMN "idCategoria" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."categoria_idCategoria_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 32857)
-- Name: marca; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.marca (
    "idMarca" integer NOT NULL,
    "marNombre" text NOT NULL
);


ALTER TABLE public.marca OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 32856)
-- Name: marca_idMarca_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."marca_idMarca_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."marca_idMarca_seq" OWNER TO postgres;

--
-- TOC entry 3346 (class 0 OID 0)
-- Dependencies: 211
-- Name: marca_idMarca_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."marca_idMarca_seq" OWNED BY public.marca."idMarca";


--
-- TOC entry 216 (class 1259 OID 32902)
-- Name: marca_idMarca_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.marca ALTER COLUMN "idMarca" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."marca_idMarca_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 32865)
-- Name: producto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producto (
    "idProducto" integer NOT NULL,
    "proNombre" text NOT NULL,
    "proDescripcion" text NOT NULL,
    "categoria_idCategoria" integer NOT NULL,
    "marca_idMarca" integer NOT NULL
);


ALTER TABLE public.producto OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 32909)
-- Name: producto_idProducto_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.producto ALTER COLUMN "idProducto" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."producto_idProducto_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 32882)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    "idUsuario" integer NOT NULL,
    id_user text NOT NULL,
    "usuName" text NOT NULL,
    "usuEmail" text NOT NULL,
    "usuAvatar" text NOT NULL,
    "usuAuth" text NOT NULL
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 32891)
-- Name: usuario_idUsuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN "idUsuario" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."usuario_idUsuario_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3331 (class 0 OID 32848)
-- Dependencies: 210
-- Data for Name: categoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categoria ("idCategoria", "catNombre") FROM stdin;
\.


--
-- TOC entry 3333 (class 0 OID 32857)
-- Dependencies: 212
-- Data for Name: marca; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.marca ("idMarca", "marNombre") FROM stdin;
1	Adidas
\.


--
-- TOC entry 3334 (class 0 OID 32865)
-- Dependencies: 213
-- Data for Name: producto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.producto ("idProducto", "proNombre", "proDescripcion", "categoria_idCategoria", "marca_idMarca") FROM stdin;
\.


--
-- TOC entry 3335 (class 0 OID 32882)
-- Dependencies: 214
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario ("idUsuario", id_user, "usuName", "usuEmail", "usuAvatar", "usuAuth") FROM stdin;
\.


--
-- TOC entry 3347 (class 0 OID 0)
-- Dependencies: 209
-- Name: categoria_idCategoria_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."categoria_idCategoria_seq"', 1, false);


--
-- TOC entry 3348 (class 0 OID 0)
-- Dependencies: 217
-- Name: categoria_idCategoria_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."categoria_idCategoria_seq1"', 1, false);


--
-- TOC entry 3349 (class 0 OID 0)
-- Dependencies: 211
-- Name: marca_idMarca_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."marca_idMarca_seq"', 1, false);


--
-- TOC entry 3350 (class 0 OID 0)
-- Dependencies: 216
-- Name: marca_idMarca_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."marca_idMarca_seq1"', 1, false);


--
-- TOC entry 3351 (class 0 OID 0)
-- Dependencies: 218
-- Name: producto_idProducto_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."producto_idProducto_seq"', 1, false);


--
-- TOC entry 3352 (class 0 OID 0)
-- Dependencies: 215
-- Name: usuario_idUsuario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."usuario_idUsuario_seq"', 3, true);


--
-- TOC entry 3182 (class 2606 OID 32908)
-- Name: categoria categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categoria
    ADD CONSTRAINT categoria_pkey PRIMARY KEY ("idCategoria");


--
-- TOC entry 3184 (class 2606 OID 32904)
-- Name: marca marca_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marca
    ADD CONSTRAINT marca_pkey PRIMARY KEY ("idMarca");


--
-- TOC entry 3186 (class 2606 OID 32911)
-- Name: producto producto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT producto_pkey PRIMARY KEY ("idProducto");


--
-- TOC entry 3188 (class 2606 OID 32893)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY ("idUsuario");


--
-- TOC entry 3190 (class 2606 OID 32917)
-- Name: producto fk_categoria; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT fk_categoria FOREIGN KEY ("categoria_idCategoria") REFERENCES public.categoria("idCategoria") NOT VALID;


--
-- TOC entry 3189 (class 2606 OID 32912)
-- Name: producto fk_marca; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT fk_marca FOREIGN KEY ("marca_idMarca") REFERENCES public.marca("idMarca") NOT VALID;


-- Completed on 2024-01-17 21:52:43

--
-- PostgreSQL database dump complete
--

